version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alexandermolodtsov/taski_backend:latest  # Используем образ из Docker Hub
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    image: alexandermolodtsov/taski_frontend:latest  # Используем образ из Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: alexandermolodtsov/taski_gateway:latest  # Используем образ из Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
